apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: django-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - name: api
        image: nikhil101/django-k8s:1.0 

