apiVersion: v1
kind: Service
metadata:
  name: django-k8s-svc
  #annotations:
  #  cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
status:
  loadBalancer:
     
