apiVersion: v1
kind: Service
metadata:
  name: my-service-django
spec:
  type: LoadBalancer 
  selector:
    app: web
  ports:
  - nodePort: 30819
    port: 8000
    protocol: TCP
    targetPort: 8000
